server {
    server_name __ADDRESS__;
    include /etc/nginx/include/vhost-head.conf;
    include /etc/nginx/certificat/__DOMAIN__.conf;

    location / {
        proxy_pass http://127.0.0.1:__PORT__;
        include /etc/nginx/include/proxy.conf;
    }
}

server {
    server_name __ADDRESS__;
    include /etc/nginx/include/vhost-http-redirect.conf;
}
