TYPE="docker-compose"
DESCRIPTION="Fider - feedback / votes feature requests open-source (Go + Postgres)"

INFISICAL_PATH="/services/fider"

DATA_DIR="/home/$VPS_USER/data/fider"

RESTORE_ON_INSTALL=yes
