services:
  app:
    image: nginxdemos/hello:latest
    container_name: monservice
    restart: unless-stopped
    env_file:
      - /etc/secrets/monservice.env
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./data:/data
