server {
    server_name __ADRESS__;
    include /etc/nginx/include/vhost-head.conf;
    include /etc/nginx/certificat/__DOMAIN__.conf;

    access_log /var/log/nginx/__ADRESS__.access.log;
    error_log  /var/log/nginx/__ADRESS__.error.log;

    location / {
        proxy_pass http://127.0.0.1:__PORT__;
        proxy_read_timeout 300;
        proxy_send_timeout 300;
        include /etc/nginx/include/proxy.conf;
    }
}

server {
    server_name __ADRESS__;
    include /etc/nginx/include/vhost-http-redirect.conf;
}
