services:
  pdf:
    image: frooodle/s-pdf:latest
    container_name: pdf
    restart: unless-stopped
    environment:
      - SECURITY_ENABLELOGIN=false
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    ports:
      - "127.0.0.1:8097:8080"
    volumes:
      - ${DATA_DIR}/configs:/configs
      - ${DATA_DIR}/logs:/logs
      - ${DATA_DIR}/tessdata:/usr/share/tessdata
